---
title: "MPP-E1180: Collaborative Social Data Analysis Assignment 2"
author: "Camila Vieira & Tarun Khanna"
date: "28 October 2016"
output: pdf_document
bibliography: 
- bibliography.bib
- RpackageCitations.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkgs <- c('dplyr', 'ggplot2')
#repmis::LoadandCite(pkgs, file = 'RpackageCitations.bib')

```

## Introduction

Today it is widely known the fact that climate change imposes real challenges to societies' environmental and economic wellbeing. This state of affairs urges us to think on ways to cope with the effects of climate change as well as finding potential alternatives to the roots of this human-caused phenomenon. Consequently, this pressure has put into question the traditional energy sources in use which have contributed to high levels of pollution and greenhouse gas emissions worldwide. Renewable energy adoption constitutes a means to deal with this challenge and renewable energy sources have been increasingly adopted worldwide for being a consistent way of improving energy efficiency by reducing energy consumption levels. Recent studies of @eyraud2011s and @del2014determinants identified that renewable energy sources will be the key drivers of the energy sector in coming years. Our main goal with this research project is to identify what are the determinants of investments in renewable sources of energy, namely wind and solar power energy sources, across European countries and to what extend factors, such as economic growth, changes in fuel prices, and interest rates have a significant impact on green energy investments. 

##Literature Review

According to @eyraud2011s, green investment can be defined as "investments intended to significantly reduce air pollutants and greenhouse gas emissions (GHG), without significantly reducing the production and consumption of non-energy goods". @ilas2014macroeconomic shares Eyraud's understanding and use 'green investments' and 'investments in renewable resources' interchangeably. 

Two thirds of total carbon dioxide emissions in the world come from the energy sector and their effect on human livelihood is increasingly negative. There are two potential ways of offsetting the impact of such emissions - adaptation and mitigation. While adaptation refers to the efforts to limit human exposure to climate change, mitigation is related to human activities intended to reduce the magnitude of climate change and its impact on human life. Mitigation further involves a two-fold strategy - reduction of carbon dioxide emissions through efficiency gains in energy consumption and production, and the shift to other, cleaner forms of energy production through the adoption of alternative sources.

@romano2011investments analyzes the driving of investments in renewable energy sources in low carbon and high carbon economies. This author argues that there are different ways of assessing the development of renewable energy sources in the literature. One method is to measure the replacement of traditional energy sources in the total energy supply while the other way which is also mentioned by @bird2005policies is to measure the total amount of renewable enegy produced. Each of those approaches were used by @marques2010motivations and @carley2009state. Marques et al. use the contribution of renewable to energy supply as a percentage of
total primary energy supply while Carley focuses on the yearly electricity generation from renewable energy sources.

By adopting Carley's approach, @romano2011investments conducted a dynamic panel analysis of the investments in renewable sources from 1980 to 2008 in a sample of 29 countries with distinct economic and social structures as well as different levels of economic development. The results of this study show that there is a continuity of
investment behavior in those countries that have shown sensitivity towards renewable energy sources. Moreover, it shows that countries with traditionally stable high income tend to show more attention to technologies with lower environmental impact and improved energy efficiency in comparison with fast-growing countries. Authors also concluded that the presence of nuclear power plants, for example, may affect investments in renewable energy sources.

Another interesting study on green investments was conducted by @ilas2014macroeconomic. The increasing importance of generating cleaner energy as a mitigation measure led the IMF to publish a article in its 2013 Energy Policy Journal containing explanation and trend analysis of the green investments. This research articles served as a bases for @ilas2014macroeconomic study on the factors affecting green investments at an international level in which the authors analyzed macroeconomic and political factors in different types of investment in green technologies, including low-emission energy supply, energy efficiency in energy-consuming sectors, and carbon sequestration, in 35 countries from 2000 to 2012. The analysis demonstrated that GDP per capita has a positive impact over investments in green technologies, while GDP growth and variables related to human development capacity as well as technological progress were both statistically insignificant.

Taking into account those previous studies we now aim to verify the determinants of green investments across the 28 countries of the European Union between 2000 and 2015. 


## Determinants of Renewable Energy 

This research aims to identify the key determinants of green investments in renewable energy sources in Europe. This is done by analyzing data on economic factors which may be responsible for delimiting a scenario for investment opportunities in wind and solar energy sources. We analyze this project having the following hypotheses. 

* Economic growth and income generate a higher demand for energy and clean air as well as the economic means of adopting new technology.

* Innovation is essential for advancements in the energy sector as to guarantee environmental-friendly efficiency. It means that human capital and new technologies may play an important role behind green investments. Therefore, we can attest the role of innovation in investments in renewable energy sources by verifying the number of renewable energy patents filed in each country.

* The macroeconomic theory on interest rates, which states that low interest rates are beneficial for long-run investments as it ensures availiability of larger amounts of capital. 

* The costs of fossil fuels' energy. The higher the prices of fossil fuels give an incentive for a reduction in renewable energy sources costs. Therefore, we can assume that increases in fossil fuels' prices have a positive effect on the green investments. Crude oil price is commonly used as reference price in the fossil fuel
markets. An example of this is the prices of natural gas which are often indexed to oil prices.

* The use of energy from fossil fuels shows consumption level as a percent of total energy use while the ratios of imported energy can shows us to what extent the dependence of countries on the energy generated elsewhere impacts investments in wind and solar energy sources. 


## Data Sources and Methodology

A cross-country analysis will be conducted by taking into account historical data of EU-28 countries from World Bank's World Development Indicators, Eurostat and OPEC databases covering the period 2010-2015. 
Data sources to be used in this study are all in .csv format. The main challenges related to data access include conducting proper webscraping and cleaning as to allow for effective data merging which we believe is essential for the presentation of our results. 

A panel data approach will be used to assess the determinants of green investments. The model is estimated in real terms using fixed effects methodology. The impact on green investment is calculated on the basis of covarities exposed in the previous section and takes into account country specific fixed effects.


##References

@R-dplyr and @CiteR works on R Programming were used as reference for this research proposal.

[^KEY]: This is a footnote.


